"""Initial migration

Revision ID: a9464a6c8aa4
Revises: 
Create Date: 2025-09-21 21:35:37.996063

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a9464a6c8aa4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade the database schema"""
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('last_round_stats',
    sa.Column('original_player_id', sa.String(length=36), nullable=True, comment='ID игрока из основной таблицы'),
    sa.Column('tracking_status', postgresql.ENUM('non interesting', 'interesting', 'to watch', 'my player', name='tracking_status_enum', create_type=False), nullable=True, comment='Статус отслеживания (копия из основной таблицы)'),
    sa.Column('tournament_id', sa.Integer(), nullable=False, comment='ID турнира'),
    sa.Column('player_number', sa.Integer(), nullable=True, comment='Номер игрока'),
    sa.Column('player_name', sa.String(length=255), nullable=False, comment='Имя игрока'),
    sa.Column('team_name', sa.String(length=255), nullable=False, comment='Команда'),
    sa.Column('age', sa.Integer(), nullable=True, comment='Возраст'),
    sa.Column('height', sa.String(length=10), nullable=True, comment='Рост'),
    sa.Column('weight', sa.String(length=10), nullable=True, comment='Вес'),
    sa.Column('citizenship', sa.String(length=100), nullable=True, comment='Гражданство'),
    sa.Column('player_index', sa.String(length=50), nullable=True, comment='Индекс игрока'),
    sa.Column('minutes_played', sa.Integer(), nullable=True, comment='Минуты на поле'),
    sa.Column('position', sa.String(length=50), nullable=True, comment='Позиция'),
    sa.Column('goals', sa.Integer(), nullable=True, comment='Голы'),
    sa.Column('assists', sa.Integer(), nullable=True, comment='Ассисты'),
    sa.Column('shots', sa.Integer(), nullable=True, comment='Удары'),
    sa.Column('shots_on_target', sa.Integer(), nullable=True, comment='Удары в створ'),
    sa.Column('passes_total', sa.Integer(), nullable=True, comment='Передачи'),
    sa.Column('passes_accuracy', sa.Float(), nullable=True, comment='Точность передач, %'),
    sa.Column('yellow_cards', sa.Integer(), nullable=True, comment='Жёлтые карточки'),
    sa.Column('red_cards', sa.Integer(), nullable=True, comment='Красные карточки'),
    sa.Column('xg', sa.Float(), nullable=True, comment='xG'),
    sa.Column('round_number', sa.Integer(), nullable=True, comment='Номер тура'),
    sa.Column('upload_timestamp', sa.String(length=50), nullable=True, comment='Время загрузки файла'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Уникальный идентификатор записи'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время последнего обновления записи'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('idx_last_round_original_id', 'last_round_stats', ['original_player_id'], unique=False)
    op.create_index('idx_last_round_player_name', 'last_round_stats', ['player_name'], unique=False)
    op.create_index('idx_last_round_tournament', 'last_round_stats', ['tournament_id'], unique=False)
    op.create_index('idx_last_round_tracking', 'last_round_stats', ['tracking_status'], unique=False)
    op.create_table('players_stats_raw',
    sa.Column('tracking_status', postgresql.ENUM('non interesting', 'interesting', 'to watch', 'my player', name='tracking_status_enum', create_type=False), nullable=False, comment='Статус отслеживания игрока'),
    sa.Column('tournament_id', sa.Integer(), nullable=False, comment='ID турнира: 0=МФЛ, 1=ЮФЛ-1, 2=ЮФЛ-2, 3=ЮФЛ-3'),
    sa.Column('player_number', sa.Integer(), nullable=True, comment='Номер игрока в команде'),
    sa.Column('player_name', sa.String(length=255), nullable=False, comment='Имя игрока'),
    sa.Column('team_name', sa.String(length=255), nullable=False, comment='Название команды'),
    sa.Column('age', sa.Integer(), nullable=True, comment='Возраст игрока'),
    sa.Column('height', sa.String(length=10), nullable=True, comment='Рост игрока'),
    sa.Column('weight', sa.String(length=10), nullable=True, comment='Вес игрока'),
    sa.Column('citizenship', sa.String(length=100), nullable=True, comment='Гражданство игрока'),
    sa.Column('player_index', sa.String(length=50), nullable=True, comment='Индекс игрока'),
    sa.Column('minutes_played', sa.Integer(), nullable=True, comment='Количество минут на поле'),
    sa.Column('position', sa.String(length=50), nullable=True, comment='Игровая позиция'),
    sa.Column('goal_errors', sa.Integer(), nullable=True, comment='Голевые ошибки'),
    sa.Column('rough_errors', sa.Integer(), nullable=True, comment='Грубые ошибки'),
    sa.Column('yellow_cards', sa.Integer(), nullable=True, comment='Жёлтые карточки'),
    sa.Column('red_cards', sa.Integer(), nullable=True, comment='Красные карточки'),
    sa.Column('fouls_committed', sa.Integer(), nullable=True, comment='Фолы совершённые'),
    sa.Column('fouls_suffered', sa.Integer(), nullable=True, comment='Фолы на игроке'),
    sa.Column('goals', sa.Integer(), nullable=True, comment='Голы'),
    sa.Column('assists', sa.Integer(), nullable=True, comment='Передачи голевые (ассисты)'),
    sa.Column('goal_attempts', sa.Integer(), nullable=True, comment='Голевые моменты'),
    sa.Column('goal_attempts_successful', sa.Integer(), nullable=True, comment='Голевые моменты удачные'),
    sa.Column('goal_attempts_success_rate', sa.Float(), nullable=True, comment='Голевые моменты удачные, %'),
    sa.Column('goal_moments_created', sa.Integer(), nullable=True, comment='Голевые моменты создал'),
    sa.Column('goal_attacks_participation', sa.Integer(), nullable=True, comment='Участие в голевых атаках'),
    sa.Column('shots', sa.Integer(), nullable=True, comment='Удары'),
    sa.Column('shots_on_target', sa.Integer(), nullable=True, comment='Удары в створ'),
    sa.Column('xg', sa.Float(), nullable=True, comment='xG (ожидаемые голы)'),
    sa.Column('passes_total', sa.Integer(), nullable=True, comment='Передачи всего'),
    sa.Column('passes_accuracy', sa.Float(), nullable=True, comment='Передачи точные, %'),
    sa.Column('passes_key', sa.Integer(), nullable=True, comment='Передачи ключевые'),
    sa.Column('passes_key_accuracy', sa.Float(), nullable=True, comment='Передачи ключевые точные, %'),
    sa.Column('crosses', sa.Integer(), nullable=True, comment='Навесы'),
    sa.Column('crosses_accuracy', sa.Float(), nullable=True, comment='Навесы точные, %'),
    sa.Column('passes_progressive', sa.Integer(), nullable=True, comment='Передачи прогрессивные'),
    sa.Column('passes_progressive_accuracy', sa.Float(), nullable=True, comment='Передачи прогрессивные точные, %'),
    sa.Column('passes_progressive_clean', sa.Integer(), nullable=True, comment='Передачи прогрессивные чистые'),
    sa.Column('passes_long', sa.Integer(), nullable=True, comment='Передачи длинные'),
    sa.Column('passes_long_accuracy', sa.Float(), nullable=True, comment='Передачи длинные точные, %'),
    sa.Column('passes_super_long', sa.Integer(), nullable=True, comment='Передачи сверхдлинные'),
    sa.Column('passes_super_long_accuracy', sa.Float(), nullable=True, comment='Передачи сверхдлинные точные, %'),
    sa.Column('passes_final_third', sa.Integer(), nullable=True, comment='Передачи вперёд в финальную треть'),
    sa.Column('passes_final_third_accuracy', sa.Float(), nullable=True, comment='Передачи вперёд в финальную треть точные, %'),
    sa.Column('passes_penalty_area', sa.Integer(), nullable=True, comment='Передачи в штрафную'),
    sa.Column('passes_penalty_area_accuracy', sa.Float(), nullable=True, comment='Передачи в штрафную точные, %'),
    sa.Column('passes_for_shot', sa.Integer(), nullable=True, comment='Передачи под удар'),
    sa.Column('duels_total', sa.Integer(), nullable=True, comment='Единоборства всего'),
    sa.Column('duels_success_rate', sa.Float(), nullable=True, comment='Единоборства удачные, %'),
    sa.Column('duels_defensive', sa.Integer(), nullable=True, comment='Единоборства в обороне'),
    sa.Column('duels_defensive_success_rate', sa.Float(), nullable=True, comment='Единоборства в обороне удачные, %'),
    sa.Column('duels_offensive', sa.Integer(), nullable=True, comment='Единоборства в атаке'),
    sa.Column('duels_offensive_success_rate', sa.Float(), nullable=True, comment='Единоборства в атаке удачные, %'),
    sa.Column('duels_aerial', sa.Integer(), nullable=True, comment='Единоборства вверху'),
    sa.Column('duels_aerial_success_rate', sa.Float(), nullable=True, comment='Единоборства вверху удачные, %'),
    sa.Column('dribbles', sa.Integer(), nullable=True, comment='Обводки'),
    sa.Column('dribbles_success_rate', sa.Float(), nullable=True, comment='Обводки удачные, %'),
    sa.Column('dribbles_final_third', sa.Integer(), nullable=True, comment='Обводки в финальной трети'),
    sa.Column('dribbles_final_third_success_rate', sa.Float(), nullable=True, comment='Обводки в финальной трети удачные, %'),
    sa.Column('tackles', sa.Integer(), nullable=True, comment='Отборы'),
    sa.Column('tackles_success_rate', sa.Float(), nullable=True, comment='Отборы удачные, %'),
    sa.Column('interceptions', sa.Integer(), nullable=True, comment='Перехваты'),
    sa.Column('recoveries', sa.Integer(), nullable=True, comment='Подборы'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Дополнительные заметки об игроке'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Уникальный идентификатор записи'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время последнего обновления записи'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('idx_goals_assists', 'players_stats_raw', ['goals', 'assists'], unique=False)
    op.create_index('idx_minutes_played', 'players_stats_raw', ['minutes_played'], unique=False)
    op.create_index('idx_player_name', 'players_stats_raw', ['player_name'], unique=False)
    op.create_index('idx_position', 'players_stats_raw', ['position'], unique=False)
    op.create_index('idx_team_name', 'players_stats_raw', ['team_name'], unique=False)
    op.create_index('idx_tournament_id', 'players_stats_raw', ['tournament_id'], unique=False)
    op.create_index('idx_tracking_status', 'players_stats_raw', ['tracking_status'], unique=False)
    op.create_table('position_averages',
    sa.Column('position', sa.String(length=50), nullable=False, comment='Игровая позиция'),
    sa.Column('tournament_id', sa.Integer(), nullable=False, comment='ID турнира'),
    sa.Column('avg_goals_per_90', sa.Float(), nullable=True, comment='Средние голы per 90'),
    sa.Column('avg_assists_per_90', sa.Float(), nullable=True, comment='Средние ассисты per 90'),
    sa.Column('avg_shots_per_90', sa.Float(), nullable=True, comment='Средние удары per 90'),
    sa.Column('avg_passes_per_90', sa.Float(), nullable=True, comment='Средние передачи per 90'),
    sa.Column('avg_passes_accuracy', sa.Float(), nullable=True, comment='Средняя точность передач, %'),
    sa.Column('avg_tackles_per_90', sa.Float(), nullable=True, comment='Средние отборы per 90'),
    sa.Column('avg_interceptions_per_90', sa.Float(), nullable=True, comment='Средние перехваты per 90'),
    sa.Column('avg_duels_success_rate', sa.Float(), nullable=True, comment='Средний % выигранных единоборств'),
    sa.Column('avg_xg_per_90', sa.Float(), nullable=True, comment='Среднее xG per 90'),
    sa.Column('players_count', sa.Integer(), nullable=True, comment='Количество игроков в выборке'),
    sa.Column('last_calculated', sa.String(length=50), nullable=True, comment='Дата последнего расчёта'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Уникальный идентификатор записи'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время последнего обновления записи'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('position')
    )
    op.create_index('idx_position_tournament', 'position_averages', ['position', 'tournament_id'], unique=False)
    op.drop_table('tournaments')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database schema"""
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournaments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('short_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tournaments_pkey'),
    sa.UniqueConstraint('name', name='tournaments_name_key'),
    sa.UniqueConstraint('short_code', name='tournaments_short_code_key'),
    comment='Справочник турниров/лиг'
    )
    op.drop_index('idx_position_tournament', table_name='position_averages')
    op.drop_table('position_averages')
    op.drop_index('idx_tracking_status', table_name='players_stats_raw')
    op.drop_index('idx_tournament_id', table_name='players_stats_raw')
    op.drop_index('idx_team_name', table_name='players_stats_raw')
    op.drop_index('idx_position', table_name='players_stats_raw')
    op.drop_index('idx_player_name', table_name='players_stats_raw')
    op.drop_index('idx_minutes_played', table_name='players_stats_raw')
    op.drop_index('idx_goals_assists', table_name='players_stats_raw')
    op.drop_table('players_stats_raw')
    op.drop_index('idx_last_round_tracking', table_name='last_round_stats')
    op.drop_index('idx_last_round_tournament', table_name='last_round_stats')
    op.drop_index('idx_last_round_player_name', table_name='last_round_stats')
    op.drop_index('idx_last_round_original_id', table_name='last_round_stats')
    op.drop_table('last_round_stats')
    # ### end Alembic commands ###


