"""Initial migration

Revision ID: a3165bf24add
Revises: a9464a6c8aa4
Create Date: 2025-09-21 21:55:01.803358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3165bf24add'
down_revision = 'a9464a6c8aa4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade the database schema"""
# ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'last_round_stats', ['id'])
    op.create_unique_constraint(None, 'players_stats_raw', ['id'])
    op.create_unique_constraint(None, 'position_averages', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database schema"""
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'position_averages', type_='unique')
    op.drop_constraint(None, 'players_stats_raw', type_='unique')
    op.drop_constraint(None, 'last_round_stats', type_='unique')
    # ### end Alembic commands ###


